"""Spanish sentence templates per theme (what a strength / weakness means, and what to do).

``side`` is the side of the game the stat belongs to for the team itself; in rival mode
the recommended action lands on the opposite side (their offence -> our defence).
Keys: s_own / w_own = strength / weakness of our team, s_riv / w_riv = threat /
opportunity when the team is the opponent, drill = training focus when it is our
weakness, neutralize / exploit = rival game-plan actions.
"""
from typing import Dict

THEMES: Dict[str, Dict[str, str]] = {
    "scoring": dict(
        side="ofensiva",
        s_own="Capacidad anotadora por encima de la mayoría de la liga: base para marcar el ritmo del partido.",
        w_own="Anotación por debajo de la liga: faltan recursos para generar puntos con regularidad.",
        s_riv="Anotador temible: obliga a defender cada posesión sin concesiones.",
        w_riv="Les cuesta anotar: presionar el balón y alargar sus posesiones.",
        drill="Trabajar la generación de tiros de calidad (juego en transición y acciones de dos hombres).",
        neutralize="Reducir sus posesiones fáciles: replegar rápido y cerrar las líneas de pase.",
        exploit="Forzar un partido de pocas posesiones donde les cueste anotar.",
    ),
    "defense": dict(
        side="defensiva",
        s_own="Defensa sólida: concede pocos puntos respecto a la liga.",
        w_own="Concede más puntos que la mayoría de equipos: la defensa es un punto débil.",
        s_riv="Defensa muy sólida: costará anotar, hay que mover el balón y buscar tiros liberados.",
        w_riv="Defensa permeable: atacar rápido y sin dudar.",
        drill="Reforzar principios defensivos: ayudas, rotaciones y comunicación.",
        neutralize="Atacar con paciencia y circular el balón para romper su defensa.",
        exploit="Acelerar el juego y atacar el aro desde las primeras fases.",
    ),
    "def_rebound": dict(
        side="defensiva",
        s_own="Domina el rebote defensivo: cierra las posesiones y alimenta el contraataque.",
        w_own="Concede segundas oportunidades por falta de rebote defensivo.",
        s_riv="Controla su tablero defensivo: costará correr tras el rebote.",
        w_riv="Débil en el rebote defensivo: enviar jugadores al rebote ofensivo.",
        drill="Ejercicios de bloqueo de rebote y responsabilidades de bloqueo/rebote.",
        neutralize="Limitar el rebote ofensivo y priorizar el balance defensivo.",
        exploit="Insistir en el rebote ofensivo para conseguir segundas oportunidades.",
    ),
    "off_rebound": dict(
        side="ofensiva",
        s_own="Genera segundas oportunidades con el rebote ofensivo.",
        w_own="Poca presencia en el rebote ofensivo: se pierden segundas oportunidades.",
        s_riv="Castiga con rebotes ofensivos: hay que bloquear el rebote en cada tiro.",
        w_riv="Casi no ataca el rebote ofensivo: se puede correr sin riesgo tras el tiro.",
        drill="Trabajar el rebote ofensivo y la anticipación del rebote largo.",
        neutralize="Bloquear el rebote en cada tiro y no dejarles segundas oportunidades.",
        exploit="Soltar a los jugadores rápidos en transición tras cada tiro propio.",
    ),
    "playmaking": dict(
        side="ofensiva",
        s_own="Juego colectivo fluido: reparte el balón y genera tiros asistidos.",
        w_own="Poco juego colectivo: depende de acciones individuales.",
        s_riv="Juego colectivo muy fluido: evitar que el balón circule sin oposición.",
        w_riv="Ataque individualista: apretar a sus generadores y forzar acciones aisladas.",
        drill="Mejorar la circulación de balón y la lectura de ayudas.",
        neutralize="Anticipar líneas de pase y cambiar sistemas defensivos para romper el ritmo del balón.",
        exploit="Presionar a los generadores y negar el primer pase.",
    ),
    "pressure": dict(
        side="defensiva",
        s_own="Defensa activa: roba muchos balones y convierte en puntos fáciles.",
        w_own="Poca presión sobre el balón: se generan pocas recuperaciones.",
        s_riv="Equipo que roba balón: cuidar el manejo y evitar pases arriesgados.",
        w_riv="Defiende sin presión sobre el balón: se puede atacar sin riesgo de pérdida.",
        drill="Trabajar la defensa al balón y las líneas de pase.",
        neutralize="Proteger el balón: pases cortos y claros ante su presión.",
        exploit="Atacar el balón sin temor a recuperaciones rivales.",
    ),
    "turnovers": dict(
        side="ofensiva",
        s_own="Cuida el balón: pierde pocas posesiones.",
        w_own="Pierde demasiados balones: regala posesiones al rival.",
        s_riv="Muy seguro con el balón: no esperar regalos, hay que ganar la posesión defendiendo.",
        w_riv="Pierde muchos balones: presionar y buscar el contraataque.",
        drill="Reducir pérdidas: pases, manejo bajo presión y toma de decisiones.",
        neutralize="Defender sin faltas y asegurar el rebote: no habrá pérdidas que aprovechar.",
        exploit="Presión sobre el balón y ayudas agresivas para provocar pérdidas.",
    ),
    "rim": dict(
        side="defensiva",
        s_own="Protege el aro con tapones: disuade la penetración.",
        w_own="Poca protección del aro: concede canastas cerca del cesto.",
        s_riv="Protección del aro fuerte: evitar penetraciones directas a su zona.",
        w_riv="Aro poco protegido: atacar el cesto con penetraciones y juego interior.",
        drill="Mejorar la defensa del aro: timing de ayudas y verticalidad.",
        neutralize="Preferir tiro exterior y pase interior sobre penetración directa.",
        exploit="Atacar el aro con penetración y juego interior.",
    ),
    "shoot2": dict(
        side="ofensiva",
        s_own="Muy eficiente en tiros de 2: la selección de tiro interior funciona.",
        w_own="Baja efectividad en tiros de 2: revisar calidad de tiro cerca del aro.",
        s_riv="Eficiente cerca del aro: defender el área y cerrar el pase interior.",
        w_riv="Poco acierto en tiros de 2: forzar tiros contestados dentro.",
        drill="Trabajar finalizaciones y selección de tiro en el área.",
        neutralize="Proteger la pintura y negar el pase interior.",
        exploit="Forzar los tiros de 2 con defensa cerrada en el área.",
    ),
    "shoot3": dict(
        side="ofensiva",
        s_own="Gran acierto en triples: el espaciado es un arma.",
        w_own="Bajo acierto desde el triple: el espaciado pierde efectividad.",
        s_riv="Peligroso desde el triple: salir bien a los lanzadores.",
        w_riv="Poco acierto exterior: se puede defender dentro y aceptar el tiro de fuera.",
        drill="Mejorar el tiro exterior: volumen de lanzamientos y tiros liberados.",
        neutralize="Salir a los tiradores y limitar los tiros liberados.",
        exploit="Cerrar la pintura y aceptar sus tiros exteriores.",
    ),
    "free_throws": dict(
        side="ofensiva",
        s_own="Acierto alto en tiros libres: cierra los partidos igualados.",
        w_own="Bajo acierto en tiros libres: se pierden puntos fáciles.",
        s_riv="Seguro desde la línea: evitar faltas innecesarias.",
        w_riv="Falla desde la línea: hacer falta táctica en los finales ajustados.",
        drill="Rutinas de tiros libres con fatiga y presión.",
        neutralize="Evitar faltas innecesarias sobre sus mejores tiradores.",
        exploit="En finales igualados, faltar a sus peores tiradores de tiros libres.",
    ),
    "free_throw_rate": dict(
        side="ofensiva",
        s_own="Llega con frecuencia a la línea de tiros libres.",
        w_own="Pocos tiros libres: poco ataque al aro y poca generación de faltas.",
        s_riv="Provoca muchas faltas: defender sin contacto innecesario.",
        w_riv="Genera pocos tiros libres: se puede defender con más contacto.",
        drill="Atacar el aro con más agresividad y buscar contacto.",
        neutralize="Defender con verticalidad y sin faltas evitables.",
        exploit="Defender con contacto ya que casi no atacan la línea.",
    ),
    "shooting_eff": dict(
        side="ofensiva",
        s_own="Eficiencia de tiro alta: cada tiro vale más que en la media de la liga.",
        w_own="Eficiencia de tiro baja: se necesitan tiros de más calidad.",
        s_riv="Muy eficiente al tirar: forzar tiros difíciles y negar los más rentables.",
        w_riv="Tira con poca eficiencia: mantener su volumen de tiros difíciles.",
        drill="Mejorar la selección de tiro y la calidad de las acciones ofensivas.",
        neutralize="Negar sus tiros más rentables (triples y cercanos al aro).",
        exploit="Forzar tiros de media distancia contestados.",
    ),
    "tempo": dict(
        side="ofensiva",
        s_own="Ritmo de juego diferencial.",
        w_own="Ritmo de juego diferencial.",
        s_riv="Ritmo de juego diferencial.",
        w_riv="Ritmo de juego diferencial.",
        drill="Definir el ritmo de partido deseado.",
        neutralize="Imponer el ritmo propio.",
        exploit="Imponer el ritmo propio.",
    ),
    "shot_mix": dict(
        side="ofensiva",
        s_own="Selección de tiro exterior marcada.",
        w_own="Selección de tiro exterior marcada.",
        s_riv="Selección de tiro exterior marcada.",
        w_riv="Selección de tiro exterior marcada.",
        drill="Equilibrar el tiro exterior e interior.",
        neutralize="Preparar la defensa del perímetro.",
        exploit="Preparar la defensa del perímetro.",
    ),
    "off_rating": dict(
        side="ofensiva",
        s_own="Ataque muy eficiente por posesión.",
        w_own="Ataque poco eficiente por posesión.",
        s_riv="Ataque muy eficiente: la defensa tendrá que ser colectiva y sin errores.",
        w_riv="Ataque poco eficiente: una defensa sólida puede decidir el partido.",
        drill="Revisar el sistema ofensivo: calidad de tiro y ejecución por posesión.",
        neutralize="Defender cada posesión sin concesiones.",
        exploit="Defender fuerte y no regalar canastas fáciles.",
    ),
    "def_rating": dict(
        side="defensiva",
        s_own="Defensa muy eficiente por posesión.",
        w_own="Defensa poco eficiente por posesión.",
        s_riv="Defensa muy eficiente: prepararse para un partido de pocas ventajas.",
        w_riv="Defensa poco eficiente: atacar con orden aprovechará sus errores.",
        drill="Revisar el sistema defensivo: cobertura de bloqueos y ayudas.",
        neutralize="Ser paciente en ataque y buscar ventajas con el balón en movimiento.",
        exploit="Atacar con orden: cada posesión bien ejecutada rinde.",
    ),
    "net_rating": dict(
        side="ofensiva",
        s_own="Balance global muy positivo por cada 100 posesiones.",
        w_own="Balance global negativo por cada 100 posesiones.",
        s_riv="Equipo claramente superior en balance: el partido exige máxima concentración.",
        w_riv="Equipo con balance negativo: hay margen para ganar con un plan sólido.",
        drill="Priorizar eficiencia ofensiva y defensiva a la vez.",
        neutralize="Reducir al mínimo los errores propios.",
        exploit="Ejecutar un plan sólido y sostenido durante todo el partido.",
    ),
}

CONSISTENCY = {
    "own": {
        "inconsistent": "Muy irregular de un partido a otro: conviene estabilizarlo en los entrenamientos.",
        "consistent": "Muy estable partido a partido: es una métrica fiable del equipo.",
    },
    "rival": {
        "inconsistent": "Muy irregular: un mal día suyo es posible; mantener la presión para provocarlo.",
        "consistent": "Muy estable: se puede dar por segura, preparar el partido sobre ella.",
    },
}

FLIP = {"ofensiva": "defensiva", "defensiva": "ofensiva"}
