/** Import / show / remove the preparation package (.bpkg generated by BasketLab "Preparación live"). */
import { useState } from 'react'
import type { EngineApi } from '../engine/client'
import { decryptEnvelope } from '../package/crypto'
import type { PackageStore } from '../package/storage'
import { summarizePackage, type PackageSummary } from '../package/summary'

interface Props {
  engine: EngineApi
  store: PackageStore
  loaded?: PackageSummary | null
  onLoaded: (summary: PackageSummary) => void
  onRemoved?: () => void
}

function formatDate(iso: string): string {
  const d = new Date(iso)
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleDateString('es-ES')
}

export default function PackagePanel({ engine, store, loaded, onLoaded, onRemoved }: Props) {
  const [file, setFile] = useState<File | null>(null)
  const [pass, setPass] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function importPackage() {
    if (!file) return
    setBusy(true)
    setError(null)
    try {
      const plaintext = await decryptEnvelope(await file.text(), pass)
      await engine.start(plaintext) // the engine validates checksum and schema version
      await store.save({ plaintext, savedAt: new Date().toISOString() })
      setPass('')
      setFile(null)
      onLoaded(summarizePackage(plaintext))
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setBusy(false)
    }
  }

  async function remove() {
    await store.clear()
    onRemoved?.()
  }

  return (
    <section className="panel">
      <h2>Paquete de preparación</h2>
      {loaded ? (
        <div className="package-summary">
          <p><strong>{loaded.team}</strong> vs <strong>{loaded.rival}</strong></p>
          <p className="detail">
            Temporada {loaded.season} · creado el {formatDate(loaded.createdAt)} · {loaded.ownPlayers} jugadores propios,
            {' '}{loaded.rivalPlayers} rivales · partidos: {loaded.games.own} propios, {loaded.games.rival} rival,
            {' '}{loaded.games.league} de la liga
          </p>
          <button className="secondary" onClick={() => void remove()}>Quitar paquete</button>
        </div>
      ) : (
        <p className="detail">Sin paquete: se usa el partido de demostración.</p>
      )}

      <div className="package-import">
        <label>
          Fichero del paquete (.bpkg)
          <input type="file" accept=".bpkg,application/octet-stream,application/json"
            onChange={e => setFile(e.target.files?.[0] ?? null)} />
        </label>
        <label>
          Contraseña del paquete
          <input type="password" value={pass} onChange={e => setPass(e.target.value)} autoComplete="off" />
        </label>
        <button disabled={!file || !pass || busy} onClick={() => void importPackage()}>
          {busy ? 'Importando…' : loaded ? 'Importar otro' : 'Importar'}
        </button>
        {error && <p role="alert" className="status error">{error}</p>}
      </div>
    </section>
  )
}
