/** Demo data bundled with the app (generated by scripts/sync-engine.mjs). */
export interface DemoData {
  /** Preparation package envelope (JSON text). */
  package: string
  /** A finished FEB game (JSON text) replayed as if it were live. */
  game: string
}

export async function loadDemoData(): Promise<DemoData> {
  const [pkg, game] = await Promise.all([
    fetch(`${location.origin}/demo/package.json`).then(r => r.text()),
    fetch(`${location.origin}/demo/game.json`).then(r => r.text()),
  ])
  return { package: pkg, game }
}
